# Dual-language ~ Node.js + Java.

language: node_js

node_js: 8 # Was: "6"
  # Was: "4" << Currently gives a `deprecated` warning for lodash. (Grunt bug: 1403)

cache: npm

git:
  depth: 16

before_install:
  #- git fetch --tags --depth=16

# install: npm ci

before_script:
  - npm run copy-conf
  - npm run copy-java-pom
  #- ls static/src/js/app/ && ls app/
  - npm run echo-versions

script:
  # Note: "npm run build" duplicates "npm test".
  - npm test
  # Compile Java, removing 100s of 'Downloading ..' lines in log output ...
  - npm run compile-java-ci
  # .. Then, ensure compile errors are caught!
  - bash bin/travis-exit-java.sh

after_script:
  #- npm run weblate-stats
  - cat static/src/version.json
  - cat npm-debug.log
  - npm audit
  - npm outdated

# End.
