language: node_js
node_js:
  - "0.11"
  #- "0.10"

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - npm run setup-config-js
  - npm run setup-java
  #- ls static/src/js/app/ && ls app/
  - npm run versions

script:
  - grunt
  # Compile Java, removing 100s of 'Downloading ..' lines in log output ...
  - "mvn compile -f app/pom.xml | tee app/mvn.log | egrep '(ERROR|WARN|INFO)'"
  # .. Then, ensure compile errors are caught!
  - bash bin/travis-exit-java.sh


#End.
