language: node_js
node_js:
  #- "4"  # << Currently gives a `deprecated` warning for lodash. (Grunt bug: 1403)
  - "0.12"
  #- "0.11"
  - "0.10"

git:
  depth: 5

install:
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install

before_script:
  - npm run setup-config-js
  - npm run setup-java
  #- ls static/src/js/app/ && ls app/
  - npm run echo-versions

script:
  - grunt
  # Compile Java, removing 100s of 'Downloading ..' lines in log output ...
  - "mvn compile -f app/pom.xml | tee app/mvn.log | egrep '(ERROR|WARN|INFO)'"
  # .. Then, ensure compile errors are caught!
  - bash bin/travis-exit-java.sh

after_script:
  #- npm run weblate-stats
  #- npm run version
  - node bin/git-versions.js --all
  - cat static/src/version.json

#End.
