language: node_js
node_js:
  - "6"
  # Was: "4" << Currently gives a `deprecated` warning for lodash. (Grunt bug: 1403)
  #- "0.12"
  #- "0.10"

git:
  depth: 16

before_install:
  #- git fetch --tags --depth=16

install:
  - npm install

before_script:
  - npm run copy-conf
  - npm run copy-java-pom
  #- ls static/src/js/app/ && ls app/
  - npm run echo-versions

script:
  - npm test
  - npm run build
  # Compile Java, removing 100s of 'Downloading ..' lines in log output ...
  - npm run tr-compile-java
  # .. Then, ensure compile errors are caught!
  - bash bin/travis-exit-java.sh

after_script:
  #- npm run weblate-stats
  - cat static/src/version.json
  - cat npm-debug.log

#End.
