language: node_js
node_js:
  - "0.11"
#  - "0.10"

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - npm run versions

script:
  - grunt
  - npm run compile-java

#after_script:
